# Fetch label, symbol, and summary for a resource.
# Expects: ?this
SELECT ?label ?symbol ?summary ?prefix ?vocabulary_url WHERE {
    ?this
        rdfs:label ?label ;
        rdfs:isDefinedBy [
            :prefix ?prefix ;
            octa:subjectOf / octa:url ?vocabulary_url
        ] .

    OPTIONAL {
        ?this :symbol ?symbol .
    }

    OPTIONAL {
        GRAPH ?page {
            ?this rdfs:comment ?summary .
        }

        ?page octa:about ?this .
    }
}
