# Objects related to this one, in printable form.
# Expects: ?this ?relation
SELECT ?link ?label ?symbol WHERE {
    ?this ?relation ?obj .

    ?obj
        rdfs:label ?label ;
        :symbol ?symbol ;
        octa:subjectOf / octa:url ?link .

    OPTIONAL {
        ?obj octa:position ?position .
    }

    FILTER(?obj != ?this)
} ORDER BY ?position
