site_name: vocabulari.es
repo_url: https://github.com/octadocs/vocabulari.es
repo_name: vocabulari.es
copyright: Copyright &copy; 2020 OctaDocs

markdown_extensions:
  - admonition
  - codehilite
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - octadocs
  - search
  - macros:
      modules:
        - octadocs.macros

theme:
  name: semantic
  logo:
    image: logo.png
  custom_dir: templates
