SELECT * WHERE {
    ?ontology
        a owl:Ontology ;

        octa:title ?title ;
        rdfs:comment ?description ;

        schema:image / octa:url ?image ;
        octa:subjectOf / octa:url ?url .

    OPTIONAL {
        ?ontology octa:position ?explicit_position .
    }

    BIND(COALESCE(?explicit_position, 0) AS ?position)
} ORDER BY ?position
