# Show categories of terms for this vocabulary.
# Expects: ?vocabulary
SELECT * WHERE {
    ?iri
        a :Category ;
        :priority ?priority ;
        rdfs:label ?label ;
        :column_width ?column_width ;
        octa:about ?vocabulary .
} ORDER BY ?priority
