# Define prefixes for vocabularies
- $id: "rdfs:"
  prefix: "rdfs"
- $id: "rdf:"
  prefix: "rdf"
- $id: "rdf:Property"
  rdfs:isDefinedBy: "rdf:"

# What is a variable? Define a few variables.
- $id: Variable
- $id: s
  $type: Variable
  label: subject
  color: red
- $id: p
  $type: Variable
  label: predicate
  color: green
- $id: o
  $type: Variable
  label: object
  color: blue

- $id: cls
  $type: Variable
  label: class
  color: blue

# Now, what is an inference Rule?
- $id: Rule
  $type: rdfs:Class
- $id: given
  rdfs:domain: Rule
  rdfs:range: rdf:Statement
- $id: infer
  rdfs:domain: Rule
  rdfs:range: rdf:Statement

# An often used statement which consists of three variables.
- $id: spo
  subject: s
  predicate: p
  object: o
